version: '2'
services:
  opus_mysql:
    image: mariadb
    volumes:
      - "./dckr_mysql_data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=28DWYN7kpS
      - MYSQL_DATABASE=opus
      - MYSQL_USER=opus
      - MYSQL_PASSWORD=k1Bh9uUBp4
    restart: always

  opus_app:
    build:
      context: ./
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      # YOU MUST regenerate APP_KEY this key use: php artisan key:generate
      - APP_KEY=base64:j/vIbnfPABFzBTpGg6+E5thGt/Ze0qHO8rbxsuetcOk=
      - APP_DEBUG=true
      - APP_LOG_LEVEL=debug
      - APP_URL=http://localhost
      - OPUS_MAIL_SENDER_ADDRESS=you@domain.com
      - OPUS_MAIL_SENDER_NAME=you@domain.com
      - DB_CONNECTION=mysql
      - DB_HOST=opus_mysql
      - DB_PORT=3306
      - DB_DATABASE=opus
      - DB_USERNAME=opus
      - DB_PASSWORD=k1Bh9uUBp4
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_DRIVER=sync
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_DRIVER=smtp
      - MAIL_HOST=mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - PUSHER_APP_ID=
      - PUSHER_KEY=
      - PUSHER_SECRET=

    links:
      - opus_mysql
    restart: always
